### ISSUE TITLE
Add "do-it-all" function, similar to Sublime Mark and Move

### ISSUE THREAD

**Issue by paradox460** [JHonaker/mark-ring#1]
In the genesis of this plugin, Sublime MarkAndMove, there was a single command that could be bound, that was context sensitive.
- At an unmarked position, running the command added a "mark" to the position.
- If it was ran at a marked position (or if you double-tapped it) it would deactivate _all_ marks, and add multiple cursors to each location

The end result of this was the ability to use all marks through the document without having to rely on multiple keybindings. I could go through a document, tap my bind, and then when i'd left enough marks, tap it on an existing mark to create my editing selections

**Comment by JHonaker** [comment]
That's a good idea. Once I get some time and get my toggle function to correctly recognize being on a previously created mark, I'll make this the default behavior.

**Comment by paradox460** [comment]
Awesome, thanks!

**Comment by JHonaker** [comment]
Just wanted to let you know I implemented this. I've pushed it here, but I'm going to wait until tomorrow to publish it because I need to redo the README to reflect these changes and re-record an example.

**Comment by paradox460** [comment]
Cool, and thank you!
